import React, { useState } from 'react';
import { useDashboard } from '../../context/DashboardContext';
import { enforcerService } from '../../services/api';
import { Gavel, CheckCircle, XCircle, FileText, Download, Shield } from 'lucide-react';
import { cn } from '../../lib/utils';

const LegalPanel = () => {
  const { dmcas, refresh, notify } = useDashboard();
  const [processingId, setProcessingId] = useState(null);

  const handleApprove = async (id) => {
    try {
      setProcessingId(id);
      await enforcerService.approve(id);
      notify('success', 'Enforcer: DMCA Notice dispatched successfully.');
      refresh();
    } catch (err) {
      console.error(err);
    } finally {
      setProcessingId(null);
    }
  };

  const handleReject = async (id) => {
    try {
      setProcessingId(id);
      await enforcerService.reject(id);
      refresh();
    } catch (err) {
      console.error(err);
    } finally {
      setProcessingId(null);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">DMCA Enforcement</h2>
          <p className="text-slate-400 text-sm">Review and approve automated takedown notices generated by Agent Enforcer.</p>
        </div>
        <div className="px-4 py-2 bg-red-500/10 border border-red-500/20 rounded-xl flex items-center gap-2">
          <span className="text-xs font-bold text-red-400">{dmcas.filter(d => d.status === 'pending').length} Awaiting Approval</span>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {dmcas.map((dmca) => (
          <div key={dmca._id} className="bg-slate-900/40 border border-white/5 rounded-2xl p-6 group hover:border-red-500/20 transition-all">
            <div className="flex flex-col lg:flex-row gap-6">
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-4">
                  <div className="p-2 bg-red-500/10 rounded-lg">
                    <FileText className="w-5 h-5 text-red-400" />
                  </div>
                  <div>
                    <h4 className="font-bold text-white">DMCA Notice #{dmca._id.slice(-6)}</h4>
                    <p className="text-xs text-slate-500">Target: {dmca.platform} • Offence Tier: {dmca.escalation_tier || 'Standard'}</p>
                  </div>
                  <span className={cn(
                    "ml-auto text-[10px] font-bold px-2 py-0.5 rounded border uppercase tracking-widest",
                    dmca.status === 'pending' ? 'text-amber-400 bg-amber-400/10 border-amber-400/20' : 
                    dmca.status === 'sent' ? 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20' : 'text-slate-500 bg-slate-500/10 border-slate-500/20'
                  )}>
                    {dmca.status}
                  </span>
                </div>
                
                <div className="bg-slate-950/80 rounded-xl p-4 font-mono text-[11px] text-slate-400 h-32 overflow-y-auto mb-4 border border-white/5 whitespace-pre-wrap">
                  {dmca.notice_content}
                </div>
              </div>

              <div className="lg:w-72 flex flex-col gap-3 justify-center">
                {dmca.status === 'pending' ? (
                  <>
                    <button 
                      onClick={() => handleApprove(dmca._id)}
                      disabled={!!processingId}
                      className="w-full py-3 bg-red-500 hover:bg-red-600 disabled:opacity-50 text-white font-bold rounded-xl flex items-center justify-center gap-2 transition-all shadow-[0_0_15px_rgba(239,68,68,0.2)]"
                    >
                      {processingId === dmca._id ? <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Shield className="w-4 h-4" />}
                      Approve & Execute
                    </button>
                    <button 
                      onClick={() => handleReject(dmca._id)}
                      disabled={!!processingId}
                      className="w-full py-3 bg-white/5 hover:bg-white/10 text-slate-300 font-bold rounded-xl border border-white/10 flex items-center justify-center gap-2 transition-all"
                    >
                      <XCircle className="w-4 h-4" /> Reject (False Positive)
                    </button>
                  </>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-center space-y-2">
                    <CheckCircle className="w-8 h-8 text-emerald-500" />
                    <p className="text-sm font-bold text-white">Execution Complete</p>
                    <p className="text-[10px] text-slate-500">Notice dispatched to {dmca.platform} legal team</p>
                    <button className="mt-2 text-[10px] font-bold text-blue-400 hover:underline flex items-center gap-1">
                      <Download className="w-3 h-3" /> Download Receipt
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
        
        {dmcas.length === 0 && (
          <div className="py-20 text-center bg-slate-900/20 border border-dashed border-white/10 rounded-3xl">
            <Gavel className="w-12 h-12 text-slate-700 mx-auto mb-4" />
            <p className="text-slate-500 font-medium">No DMCA notices staged for review.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default LegalPanel;
